### ISSUE TITLE
ESP3212 orientation mirrored

### ISSUE THREAD

**Issue by robotskirts** [adamjvr/ESP32-kiCAD-Footprints#1]
The ESP3212 footprint is a mirror image of what it should be. The schematic symbol is correct with the 1 pin in the upper left and proceeding anti-clockwise around the board. The footprint has the orientation mirrored with pins counting up in the incorrect clockwise pattern.

**Comment by joshvaldes** [comment]
Hi, I updated the footprint to be properly numbered, and used it in my design. The files are here in this bitbucket repository. Thanks.

https://bitbucket.org/joshvaldes/esp3212board

**Comment by adamjvr** [comment]
Hi, I'm sorry I missed these messages. I have since realized the mistakes and corrected both of them. The ESP-32-WROOM is properly labeled and the pins are correct now. I also was able to track down the physical specifications of the ESP3212 and have since added the correct footprint.
