### ISSUE TITLE
Footprint ESP3212 is actually ESP32 Wroom

### ISSUE THREAD

**Issue by hemalchevli** [adamjvr/ESP32-kiCAD-Footprints#2]
ESP wroom is a module made by espressif, and ESP3212 module is made by Ai-Thinker. The footprint you have made using the datasheet  is actually ESP32-Wroom. As far as I've searched I've not been able to get the footprint dimensions and pin spacing of ESP3212. I've been meaning to make a breakout for my self for esp3212.
On esp wroom there are 14 pins on two side, and on ESP3212 there are 11 pins on left and right sides of the module.
Here is ESP3212
https://www.seeedstudio.com/ESP3212-Wifi-Bluetooth-Combo-Module-p-2706.html

Here is ESP32-Wroom
http://esp32.de/esp32_developer/04_esp32_devel_wroom32.jpg

Thanks for sharing your work. Cheers!

**Comment by dude8604** [comment]
My [Eagle library](https://github.com/dude8604/ESP3212-Eagle) is for the ESP3212.

**Comment by hemalchevli** [comment]
+1. Thanks for the reference image, I missed it big time.

**Comment by adamjvr** [comment]
Hi, sorry I missed this issue but I have already fixed all these issues. I was able to track down the specification on the taobao store page for the ESP3212 and have since corrected and updated my library. Please make a new issue if there are any problems with the newly updated footprints.
