### ISSUE TITLE
Inclusion on upstream kicad repo?

### ISSUE THREAD

**Issue by diegoherranz** [adamjvr/ESP32-kiCAD-Footprints#5]
Hi!

First of all thanks for sharing these symbols and footprints.

It would be great if this was included upstream on the official [kicad library repository](https://github.com/KiCad/kicad-library).

There's more info on how to contribute [here](https://github.com/KiCad/kicad-library/blob/master/CONTRIBUTING.md).

I think it would be very beneficial for the community. Would you be keen on doing it?

Thank you very much.

Diego

**Comment by adamjvr** [comment]
I would very much like to contribute to the official kicad repo, perhaps soon after the dust settles and more people test the footprints.

**Comment by diegoherranz** [comment]
Most of these footprints are now part of the official https://github.com/KiCad/kicad-symbols repo, so I'm closing this.

Thanks.
